# Generated by Django 4.2 on 2025-02-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_unit',
            field=models.CharField(default='piece', help_text='Smallest unit (e.g., piece, gram, bottle)', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='units_in_big_unit',
            field=models.PositiveIntegerField(blank=True, help_text='Number of base units in one big unit', null=True),
        ),
    ]
