# Generated by Django 5.1.7 on 2025-03-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_product_kind_product_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.CharField(blank=True, default='افتراضى', max_length=255, null=True, verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.CharField(blank=True, default='افتراضى', max_length=255, null=True, verbose_name='المورد'),
        ),
    ]
