# Generated by Django 5.2 on 2025-04-17 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المنتج')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='التصنيف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='اسم الوحدة')),
            ],
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(verbose_name='المستوى (1 للأكبر)')),
                ('conversion_factor', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='عدد الوحدات الأقل')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر التكلفة')),
                ('sell_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر البيع')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الكمية الحالية')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='inventory.product')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.unit')),
            ],
            options={
                'ordering': ['level'],
                'unique_together': {('product', 'unit')},
            },
        ),
    ]
