# Generated by Django 5.2 on 2025-04-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_supplier_alter_productunit_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productunit',
            name='sell_price',
        ),
        migrations.AddField(
            model_name='productunit',
            name='price_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر 1 (أساسي)'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='price_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر 2 (عرض)'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='price_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر 3 (VIP)'),
        ),
    ]
