# Generated by Django 5.2 on 2025-04-19 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_product_supplier_alter_productunit_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم العميل')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاريخ البيع')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالي')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('final', 'نهائية')], default='final', max_length=10, verbose_name='الحالة')),
            ],
            options={
                'verbose_name': 'فاتورة بيع',
                'verbose_name_plural': 'فواتير البيع',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر الوحدة')),
                ('line_total', models.DecimalField(decimal_places=2, editable=False, max_digits=14, verbose_name='المجموع')),
                ('product_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productunit', verbose_name='وحدة المنتج')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='فاتورة البيع')),
            ],
            options={
                'verbose_name': 'بند بيع',
                'verbose_name_plural': 'بنود البيع',
            },
        ),
    ]
